### PR TITLE
Add SequentialMessageTransformer

### PR DESCRIPTION
**Pull request by dhgarrette**
The new class chains together multiple MessageTransformer implementations.  This is an example of the Composite Pattern (https://en.wikipedia.org/wiki/Composite_pattern).

A class implementing the `MessageTransformer` interface has to define a method called `transform` that takes a `Message` as input and returns a (presumably modified) `Message`.  We will likely have many `MessageTransformer` classes, each defining some specific behavior.  For example, the `JSoupCleanMessageTransformer` uses JSoup to remove potentially dangerous HTML tags from a `Message`'s text field.

This new class, `SequentialMessageTransformer`, makes it possible to combine multiple individual `MessageTransformer` implementations.  It stores a list of `MessageTransformer` "delegates" and when it receives a `Message` to transform, it passes that message through each of its stored delegates.  For example, you'll see in the `testTransformTextSequenceOfThree` unit test that a `SequentialMessageTransformer` that stores a list of three delegates will take an input `Message` (`message0` in the code) and pass it to the first delegate, and then take the output of that, and pass it to the second, and the output of that to the third, and return the output of the third as it's final result.

The advantage of this kind of setup is that we can sort of mix-and-match message transformation behaviors, and to test them all independently.  For instance, Kingsley is going to create a transformer for replacing image URLs with HTML markup that displays the image.  So we can then use `SequentialMessageTransformer` to store a `JSoupCleanMessageTransformer` and that new one so that when a `Message` needs to be displayed, we can remove all of its problematic HTML tags AND turns its image URLs into images, and then display it.

### CODE REVIEW

**Comment by iramsharieff06** [comment]
Is this a PR that anyone can review or would you prefer if Adel reviewed it?

**Comment by dhgarrette** [comment]
@iramsharieff06 Anyone can review :-)

**Review by iramsharieff06 — COMMENTED** [review]
What does this code do at a high level so I can better understand it during the review?

**Comment by dhgarrette** [comment]
I updated the description at the top of this PR with a fuller discussion of what's going on here.  Let me know if that helps.

**Review by king751 — APPROVED** [review]
Thanks for the explanation it makes a lot more sense now.

**Pull request merged**
